name: Mastermind Manager

on:
  push:
    branches:
      - gh-pages

jobs:
  start-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Mastermind Manager
      run: npm run start
      env:
        NODE_ENV: production
