name: Start App

on:
  push:
    branches:
      - main

jobs:
  start-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Start App
      run: node server.js
      env:
        NODE_ENV: production
